name: "Changelog Update"
description: "Update the changelog when a new release is published"
branding:
  icon: "book-open"
  color: "yellow"
inputs:
  token:
    description: "GitHub token"
    required: true
  commit_message:
    description: "Commit message for the update (optional)"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.token }}
    - ${{ inputs.commit_message }}
